CREATE TABLE User (
    Id      INT AUTO_INCREMENT PRIMARY KEY,
    Name    VARCHAR(50) UNIQUE,
    Coins   INT DEFAULT 0
);

CREATE TABLE League (
    Id      INT AUTO_INCREMENT PRIMARY KEY,
    ApiID   VARCHAR(50) NOT NULL,
    Name    VARCHAR(50) NOT NULL,
    Region  VARCHAR(50) NOT NULL,
    Image   VARCHAR(150) NOT NULL
);

CREATE TABLE Team (
    Id      INT AUTO_INCREMENT PRIMARY KEY,
    Name    VARCHAR(50) NOT NULL,
    Code    VARCHAR(50) NOT NULL,
    Image   VARCHAR(150) NOT NULL
);

CREATE TABLE Game (
    Id          INT AUTO_INCREMENT PRIMARY KEY,
    Team_1      INT NOT NULL,
    Team_2      INT NOT NULL,
    League      INT NOT NULL,
    Time        TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Bets_t1     INT DEFAULT 0 NOT NULL,
    Bets_t2     INT DEFAULT 0 NOT NULL,
    Completed   TINYINT DEFAULT 0 NOT NULL,
    BlockName   VARCHAR(20) NOT NULL,
    CHECK ( Team_1 <> Team_2 ),
    FOREIGN KEY (League) REFERENCES League(Id),
    FOREIGN KEY (Team_1) REFERENCES Team(Id),
    FOREIGN KEY (Team_2) REFERENCES Team(Id)
);

CREATE TABLE Bet (
    Id      INT AUTO_INCREMENT PRIMARY KEY,
    GameId  INT NOT NULL,
    UserId  INT NOT NULL,
    Value   INT NOT NULL,
    Team    TINYINT NOT NULL,
    FOREIGN KEY (GameId) REFERENCES Game(Id),
    FOREIGN KEY (UserId) REFERENCES User(Id)
);


