name: CI Checks

on:
  push:
    branches: # <1>
      - master
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest #
    steps:

    - name: Set up Go 1.x #
      uses: actions/setup-go@v4
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory #
      uses: actions/checkout@v3

    - name: Build
      run: make -C backend/ build #

    - name: Copy Files #
      run: |
           mkdir  artifacts
           cp backend/backend artifacts/.

    - name: Archive #
      uses: actions/upload-artifact@v3
      with:
          name: backend #
          path: artifacts
